---
- name: Remove nbu agent and directories
  hosts: all
  vars:
    nbupath: "/usr/openv/netbackup"
  tasks:
  - name: Disable startup scripts
    service: name=netbackup enabled=no
  - name: Stop nbuagt
    shell: "{{ nbupath }}/bin/bp.kill_all"
    ignore_errors: yes
  - name: Remove add-on products
    package: name={{ item }} state=absent
    with_items:
      - VRTSfrnbclt
      - VRTSjanbclt
      - VRTSzhnbclt
  - name: Unregister NetBackup from LiveUpdate
    shell: "{{ nbupath }}/bin/nblu_registration -r"
    ignore_errors: yes
  - name: Unregister NetBackup from the VxUL master configuration
    shell: "{{ nbupath }}/bin/vxlogcfg -r -p 51216"
    ignore_errors: yes
  - name: Remove nbu conf package
    package: name={{ item }} state=absent
    with_items:
      - VRTSnbcfg
      - VRTSnbjava
      - VRTSnbjre
      - VRTSnbclt
      - VRTSpbx
      - VRTSnbpck
  - name: Delete leftover directories
    file: path={{ item }} state=absent
    with_items:
      - "{{ nbupath }}"
      - "/usr/openv"
  - name: Remove startup scripts
    file: path={{ item }} state=absent
    with_items:
      - "/etc/rc.d/init.d/netbackup"
      - "/etc/rc.d/rc0.d/K01netbackup"
      - "/etc/rc.d/rc1.d/K01netbackup"
      - "/etc/rc.d/rc2.d/S77netbackup"
      - "/etc/rc.d/rc3.d/S77netbackup"
      - "/etc/rc.d/rc5.d/S77netbackup"
      - "/etc/rc.d/rc6.d/K01netbackup"
  - name: Uninstall LiveUpdate
    shell: "/opt/Symantec/LiveUpdate/uninstall.sh -a"
    ignore_errors: yes
  - name: Remove LiveUpdate files
    file: path={{ item }} state=absent
    with_items:
      - "/etc/Symantec.conf"
      - "/etc/Product.Catalog.JavaLiveUpdate"
  - name: Remove Netbackup Java Console, JRE and Symantec Deduplication Agent
    package: name={{ item }} state=absent
    with_items:
      - SYMCnbjava
      - SYMCnbjre
      - SYMCpddea
      - SYMCnbclt
  - name: Remove NetBackup-Java application state data
    file: path={{ item }} state=absent
    with_items:
      - "/.veritas"
      - "/.vxss"
      - "/home/nbu"
